version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 838709283190.dkr.ecr.sa-east-1.amazonaws.com
    - REPOSITORY_URI=838709283190.dkr.ecr.sa-east-1.amazonaws.com/nginx

  build:
    commands:
    - echo Building the app on `date`
    - echo Building Docker container...
    - docker build --cache-from graphql-client -t graphql-client .
    - docker tag graphql-client:latest 838709283190.dkr.ecr.sa-east-1.amazonaws.com/nginx:latest

  post_build:
    commands:
    - echo Build complete on `date`
    - echo Pushing the Docker image...
    - docker push 838709283190.dkr.ecr.sa-east-1.amazonaws.com/nginx
